Repository GDSC-SWU/2023-SilverSurfer-SolutionChallenge, pull requests merged in 2023-03, with the labels that each got.

#9 [BE] 컨텐츠, 마이페이지, 검색 API
  server/app.js
  server/config/db.js
  server/middlewares/validateAccessToken.js
  server/routes/Auth.js
  server/routes/Content.js
  server/routes/Contribute.js
  server/routes/Mypage.js
  server/routes/Search.js
  server/util/jwt.js
  server/util/strValidate.js
Labels: feature

#10 Develop -> Main
  client/src/App.js
  client/src/GlobalStyle.jsx
  client/src/assets/card_test.jpg
  client/src/assets/icon/googleIcon.svg
  client/src/assets/icon/icon_bookmark_active.svg
  client/src/assets/icon/icon_bookmark_inactive.svg
  client/src/assets/icon/icon_menu_communication.svg
  client/src/assets/icon/icon_menu_component.svg
  client/src/assets/icon/icon_menu_main.svg
  client/src/assets/icon/icon_menu_my.svg
  client/src/assets/icon/icon_menu_project.svg
  client/src/assets/icon/icon_menu_search.svg
  client/src/assets/icon/icon_menu_style.svg
  client/src/assets/icon/icon_menu_target.svg
  client/src/assets/login_bc_img.svg
  client/src/assets/theme/index.jsx
  client/src/components/home/Card.jsx
  client/src/components/home/Guideline.jsx
  client/src/components/navigation/Menu.jsx
  client/src/components/navigation/NavigationBar.jsx
  client/src/index.js
  client/src/login/GoogleLogin.jsx
  client/src/main/HomePage.jsx
  server/app.js
  server/config/db.js
  server/middlewares/validateAccessToken.js
  server/routes/Auth.js
  server/routes/Content.js
  server/routes/Contribute.js
  server/routes/Mypage.js
  server/routes/Search.js
  server/util/jwt.js
  server/util/strValidate.js
Labels: feature

#15 [FE] 메인페이지 구현 1차
  client/src/assets/main_banner.jpg
  client/src/assets/theme/index.jsx
  client/src/components/home/Guideline.jsx
  client/src/components/home/InputBox.jsx
  client/src/main/HomePage.jsx
Labels: feature

#16 [FE] 가이드 상세 페이지 1차
  client/src/App.js
  client/src/Content/GuidePage.jsx
  client/src/assets/contentImage.jpg
  client/src/assets/guideImage.jpg
  client/src/assets/theme/index.jsx
Labels: feature

#17 [FE] 마이페이지 구현 1차
  client/src/App.js
  client/src/assets/myBackgroundImage.jpg
  client/src/assets/theme/index.jsx
  client/src/myPage/MyPage.jsx
Labels: feature

#18 [BE] 배포, API 수정사항 반영
  client/app.yaml
  client/src/API/postLogin.js
  client/src/login/GoogleLogin.jsx
  server/package-lock.json
  server/package.json
  server/routes/Auth.js
  server/routes/Mypage.js
  server/server.js
  server/util/redisCli.js
Labels: bug, infra

#19 Develop -> Main
  client/app.yaml
  client/src/API/postLogin.js
  client/src/App.js
  client/src/Content/GuidePage.jsx
  client/src/assets/contentImage.jpg
  client/src/assets/guideImage.jpg
  client/src/assets/main_banner.jpg
  client/src/assets/myBackgroundImage.jpg
  client/src/assets/theme/index.jsx
  client/src/components/home/Guideline.jsx
  client/src/components/home/InputBox.jsx
  client/src/login/GoogleLogin.jsx
  client/src/main/HomePage.jsx
  client/src/myPage/MyPage.jsx
  server/package-lock.json
  server/package.json
  server/routes/Auth.js
  server/routes/Mypage.js
  server/server.js
  server/util/redisCli.js
Labels: bug, feature, infra

#26 [BE] API 수정사항 반영, API 연결, 배포
  client/.gcloudignore
  client/build/asset-manifest.json
  client/build/favicon.ico
  client/build/index.html
  client/build/logo192.png
  client/build/logo512.png
  client/build/manifest.json
  client/build/robots.txt
  client/build/static/js/main.22333ba4.js
  client/build/static/js/main.22333ba4.js.LICENSE.txt
  client/build/static/js/main.22333ba4.js.map
  client/build/static/media/contentImage.a977b7bbaafab8cd3263.jpg
  client/build/static/media/googleIcon.e59ef52360fbceecc59e3d5e68c6aeea.svg
  client/build/static/media/guideImage.e5bc6ca663cbc34d386f.jpg
  client/build/static/media/icon_menu_communication.05f0d7dcf07902f02ccb017ed81b1cb8.svg
  client/build/static/media/icon_menu_component.746c63f3ca534a813a77679e8fba9415.svg
  client/build/static/media/icon_menu_main.b86d1c3d5a5bde88c0156146bfc32052.svg
  client/build/static/media/icon_menu_my.69952e1572e33c63772276bfe5fc0764.svg
  client/build/static/media/icon_menu_project.ca091a944dfdaded60abbc773cc87529.svg
  client/build/static/media/icon_menu_search.07892b8cbaffa20957dd3b996d8c2cc4.svg
  client/build/static/media/icon_menu_style.e052319f939479f048a7baa06436107e.svg
  client/build/static/media/icon_menu_target.9ffc2a812cf447cfea6cf8fb5c7a2e4b.svg
  client/build/static/media/login_bc_img.88ebdd76a2cbb940bc038a52762ac857.svg
  client/build/static/media/main_banner.dfff95b174ebc9b03794.jpg
  client/build/static/media/myBackgroundImage.79526d2bf05f12ecbff1.jpg
  client/src/API/postLogin.js
  client/src/components/GoogleLogin.jsx
  client/src/store/setUserInfo.js
  server/app.server.yaml
  server/package-lock.json
  server/package.json
  server/routes/Auth.js
  server/routes/Content.js
  server/server.js
  server/util/redisCli.js
Labels: feature, infra

#29 fix: Modify server url
  client/src/components/Card/UxGuide.jsx
Labels: bug

#32 [BE] API 연결, 배포
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/assets/icon/icon_search.svg
  client/src/components/Card/CardDetail.jsx
  client/src/components/UI/Search.jsx
  client/src/pages/MyPage.jsx
  client/src/pages/SearchResultPage.jsx
  server/routes/Auth.js
  server/routes/Content.js
  server/routes/Mypage.js
  server/routes/Search.js
Labels: feature, infra

#33 Develop -> Main
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/API/API.js
  client/src/GlobalStyle.jsx
  client/src/assets/icon/icon_search.svg
  client/src/components/Card/CardDetail.jsx
  client/src/components/Card/ComponentGuide.jsx
  client/src/components/Card/UxGuide.jsx
  client/src/components/UI/Card.jsx
  client/src/components/UI/Menu.jsx
  client/src/components/UI/Search.jsx
  client/src/hooks/useCardData.jsx
  client/src/hooks/useLoginCardData.jsx
  client/src/hooks/useToken.jsx
  client/src/index.js
  client/src/pages/Home.jsx
  client/src/pages/MyPage.jsx
  client/src/pages/SearchResultPage.jsx
  server/routes/Auth.js
  server/routes/Content.js
  server/routes/Mypage.js
  server/routes/Search.js
Labels: bug, feature, infra

#36 [FE] API 연동 오류 및 레이아웃 수정
  client/src/components/Card/CardDetail.jsx
  client/src/components/Card/ComponentGuide.jsx
  client/src/components/Card/StyleGuide.jsx
  client/src/components/Card/UxGuide.jsx
  client/src/components/UI/Card.jsx
  client/src/components/UI/Search.jsx
  client/src/pages/Home.jsx
  client/src/pages/MyPage.jsx
  client/src/pages/SearchResultPage.jsx
Labels: bug, feature

#37 [BE] API 연결, 세부 페이지, 네비게이션 바
  client/build/asset-manifest.json
  client/build/index.html
  client/build/static/css/main.fb8c9de5.css
  client/build/static/css/main.fb8c9de5.css.map
  client/build/static/js/main.0ae682c6.js
  client/build/static/js/main.0ae682c6.js.LICENSE.txt
  client/build/static/js/main.0ae682c6.js.map
  client/build/static/js/main.22333ba4.js
  client/build/static/js/main.22333ba4.js.map
  client/build/static/media/icon_bookmark_active.499bafff3cf4bb995201cb2b57c8d6c1.svg
  client/build/static/media/icon_bookmark_inactive.6f988ef344050c20af95c70612d0ee12.svg
  client/package-lock.json
  client/package.json
  client/src/API/API.js
  client/src/App.css
  client/src/App.js
  client/src/assets/icon/icon_menu_uxguideline.svg
  client/src/assets/thumbnailBackgroundImage.png
  client/src/components/Card/CardDetail.jsx
  client/src/components/Card/UxGuide.jsx
  client/src/components/UI/IndexBar.jsx
  client/src/components/UI/Menu.jsx
  client/src/components/UI/NavigationBar.jsx
  client/src/pages/Home.jsx
  server/app.server.yaml
Labels: bug, feature, infra

#43 [FE, BE] 클립보드 추가, 배포 마무리
  client/public/index.html
  client/src/assets/icon/icon_clipboard.svg
  client/src/assets/icon/icon_clipboard_complete.svg
  client/src/components/Card/CardDetail.jsx
  client/src/components/UI/IndexBar.jsx
Labels: bug, feature

#48 [Hotfix] axios url 수정
  client/src/components/FeedBackForm.jsx
Labels: bug
